### ISSUE TITLE
Not reporting New Nominations 

### ISSUE THREAD

**Issue by ccris02** [helikon-labs/subvt-data-android#1]
I get notification when my node loses nominations in both Polkadot and Kusama nodes but I don't get any notification with new nominations. New nominations notification is set to every 3 Epochs.

**Comment by kukabi** [comment]
Hey @ccris02! Thanks for the report, I'm going to look into it. It would be great if you can let me know if it only fails only for 3 epochs setting, or regardless.

I'm closing this issue in favor of the [issue](https://github.com/helikon-labs/subvt-backend/issues/235) in the SubVT backend repo, you may use that issue for feedback. This repo is for the data access layer of the upcoming Android app.

Cheers!
